import { registerTool } from "../toolRegistry";

import WordCounter from "./WordCounter";
import CharacterCounter from "./CharacterCounter";
import TextCaseConverter from "./TextCaseConverter";
import TextReverser from "./TextReverser";
import JSONFormatter from "./JSONFormatter";
import Base64Converter from "./Base64Converter";
import URLEncoder from "./URLEncoder";
import URLSlugGenerator from "./URLSlugGenerator";
import MorseCodeConverter from "./MorseCodeConverter";
import CSVToJSON from "./CSVToJSON";
import PasswordGenerator from "./PasswordGenerator";
import MD5Hash from "./MD5Hash";
import SHA256Hash from "./SHA256Hash";
import UUIDGenerator from "./UUIDGenerator";
import QRCodeGenerator from "./QRCodeGenerator";
import ColorPicker from "./ColorPicker";
import GradientGenerator from "./GradientGenerator";
import BMICalculator from "./BMICalculator";
import AgeCalculator from "./AgeCalculator";
import LoanCalculator from "./LoanCalculator";
import EMICalculator from "./EMICalculator";
import PercentageCalculator from "./PercentageCalculator";
import SimpleInterestCalculator from "./SimpleInterestCalculator";
import CompoundInterestCalculator from "./CompoundInterestCalculator";
import TipCalculator from "./TipCalculator";
import DiscountCalculator from "./DiscountCalculator";
import MarkupCalculator from "./MarkupCalculator";
import VATCalculator from "./VATCalculator";
import GPACalculator from "./GPACalculator";
import FactorialCalculator from "./FactorialCalculator";
import UnitConverter from "./UnitConverter";
import TemperatureConverter from "./TemperatureConverter";
import WeightConverter from "./WeightConverter";
import LengthConverter from "./LengthConverter";
import VolumeConverter from "./VolumeConverter";
import AreaConverter from "./AreaConverter";
import SpeedConverter from "./SpeedConverter";
import EnergyConverter from "./EnergyConverter";
import CurrencyConverter from "./CurrencyConverter";
import Stopwatch from "./Stopwatch";
import Timer from "./Timer";
import TimeCalculator from "./TimeCalculator";
import UptimeCalculator from "./UptimeCalculator";
import PrimeChecker from "./PrimeChecker";
import FibonacciGenerator from "./FibonacciGenerator";
import RomanNumeralConverter from "./RomanNumeralConverter";
import HexToDecimal from "./HexToDecimal";
import DecimalToBinary from "./DecimalToBinary";
import BinaryToDecimal from "./BinaryToDecimal";
import HexToRGB from "./HexToRGB";
import RGBToHex from "./RGBToHex";
import DistanceCalculator from "./DistanceCalculator";
import TextToSpeech from "./TextToSpeech";
import ScreenResolution from "./ScreenResolution";
import QRCodeScanner from "./QRCodeScanner";


registerTool("word-counter", WordCounter);
registerTool("character-counter", CharacterCounter);
registerTool("text-case-converter", TextCaseConverter);
registerTool("text-reverser", TextReverser);
registerTool("json-formatter", JSONFormatter);
registerTool("base64-converter", Base64Converter);
registerTool("url-encoder", URLEncoder);
registerTool("url-slug-generator", URLSlugGenerator);
registerTool("morse-code-converter", MorseCodeConverter);
registerTool("csv-to-json", CSVToJSON);
registerTool("password-generator", PasswordGenerator);
registerTool("md5-hash", MD5Hash);
registerTool("sha256-hash", SHA256Hash);
registerTool("uuid-generator", UUIDGenerator);
registerTool("qr-code-generator", QRCodeGenerator);
registerTool("color-picker", ColorPicker);
registerTool("gradient-generator", GradientGenerator);
registerTool("bmi-calculator", BMICalculator);
registerTool("age-calculator", AgeCalculator);
registerTool("loan-calculator", LoanCalculator);
registerTool("emi-calculator", EMICalculator);
registerTool("percentage-calculator", PercentageCalculator);
registerTool("simple-interest", SimpleInterestCalculator);
registerTool("compound-interest", CompoundInterestCalculator);
registerTool("tip-calculator", TipCalculator);
registerTool("discount-calculator", DiscountCalculator);
registerTool("markup-calculator", MarkupCalculator);
registerTool("vat-calculator", VATCalculator);
registerTool("gpa-calculator", GPACalculator);
registerTool("factorial-calculator", FactorialCalculator);
registerTool("unit-converter", UnitConverter);
registerTool("temperature-converter", TemperatureConverter);
registerTool("weight-converter", WeightConverter);
registerTool("length-converter", LengthConverter);
registerTool("volume-converter", VolumeConverter);
registerTool("area-converter", AreaConverter);
registerTool("speed-converter", SpeedConverter);
registerTool("energy-converter", EnergyConverter);
registerTool("currency-converter", CurrencyConverter);
registerTool("stopwatch", Stopwatch);
registerTool("timer", Timer);
registerTool("time-calculator", TimeCalculator);
registerTool("uptime-calculator", UptimeCalculator);
registerTool("prime-checker", PrimeChecker);
registerTool("fibonacci-generator", FibonacciGenerator);
registerTool("roman-numeral", RomanNumeralConverter);
registerTool("hex-to-decimal", HexToDecimal);
registerTool("decimal-to-binary", DecimalToBinary);
registerTool("binary-to-decimal", BinaryToDecimal);
registerTool("hex-to-rgb", HexToRGB);
registerTool("rgb-to-hex", RGBToHex);
registerTool("distance-calculator", DistanceCalculator);
registerTool("text-to-speech", TextToSpeech);
registerTool("screen-resolution", ScreenResolution);
registerTool("qr-code-scanner", QRCodeScanner);
