import { registerTool } from "../toolRegistry";

import WordCounter from "./WordCounter";
import CharacterCounter from "./CharacterCounter";
import TextCaseConverter from "./TextCaseConverter";
import TextReverser from "./TextReverser";
import JSONFormatter from "./JSONFormatter";
import Base64Converter from "./Base64Converter";
import URLEncoder from "./URLEncoder";
import URLSlugGenerator from "./URLSlugGenerator";
import MorseCodeConverter from "./MorseCodeConverter";
import CSVToJSON from "./CSVToJSON";
import PasswordGenerator from "./PasswordGenerator";
import MD5Hash from "./MD5Hash";
import SHA256Hash from "./SHA256Hash";
import UUIDGenerator from "./UUIDGenerator";
import QRCodeGenerator from "./QRCodeGenerator";
import ColorPicker from "./ColorPicker";
import GradientGenerator from "./GradientGenerator";
import BMICalculator from "./BMICalculator";
import AgeCalculator from "./AgeCalculator";
import LoanCalculator from "./LoanCalculator";
import EMICalculator from "./EMICalculator";
import PercentageCalculator from "./PercentageCalculator";
import SimpleInterestCalculator from "./SimpleInterestCalculator";
import CompoundInterestCalculator from "./CompoundInterestCalculator";
import TipCalculator from "./TipCalculator";
import DiscountCalculator from "./DiscountCalculator";
import MarkupCalculator from "./MarkupCalculator";
import VATCalculator from "./VATCalculator";
import GPACalculator from "./GPACalculator";
import FactorialCalculator from "./FactorialCalculator";
import UnitConverter from "./UnitConverter";
import TemperatureConverter from "./TemperatureConverter";
import WeightConverter from "./WeightConverter";
import LengthConverter from "./LengthConverter";
import VolumeConverter from "./VolumeConverter";
import AreaConverter from "./AreaConverter";
import SpeedConverter from "./SpeedConverter";
import EnergyConverter from "./EnergyConverter";
import CurrencyConverter from "./CurrencyConverter";
import Stopwatch from "./Stopwatch";
import Timer from "./Timer";
import TimeCalculator from "./TimeCalculator";
import UptimeCalculator from "./UptimeCalculator";
import PrimeChecker from "./PrimeChecker";
import FibonacciGenerator from "./FibonacciGenerator";
import RomanNumeralConverter from "./RomanNumeralConverter";
import HexToDecimal from "./HexToDecimal";
import DecimalToBinary from "./DecimalToBinary";
import BinaryToDecimal from "./BinaryToDecimal";
import HexToRGB from "./HexToRGB";
import RGBToHex from "./RGBToHex";
import DistanceCalculator from "./DistanceCalculator";
import TextToSpeech from "./TextToSpeech";
import ScreenResolution from "./ScreenResolution";
import QRCodeScanner from "./QRCodeScanner";
import RegexTester from "./RegexTester";
import JWTDecoder from "./JWTDecoder";
import UnixTimestampConverter from "./UnixTimestampConverter";
import HTMLEntityConverter from "./HTMLEntityConverter";
import LoremIpsumGenerator from "./LoremIpsumGenerator";
import PasswordStrengthChecker from "./PasswordStrengthChecker";
import CSSMinifier from "./CSSMinifier";
import JavaScriptMinifier from "./JavaScriptMinifier";
import MetaTagGenerator from "./MetaTagGenerator";
import RobotsTxtGenerator from "./RobotsTxtGenerator";
import XMLFormatter from "./XMLFormatter";
import XMLToJSON from "./XMLToJSON";
import JSONToXML from "./JSONToXML";
import HTMLFormatter from "./HTMLFormatter";
import SQLFormatter from "./SQLFormatter";
import URLParser from "./URLParser";
import CronExpressionGenerator from "./CronExpressionGenerator";
import HMACGenerator from "./HMACGenerator";
import TextDiffChecker from "./TextDiffChecker";
import ColorContrastChecker from "./ColorContrastChecker";
import MortgageCalculator from "./MortgageCalculator";
import ROICalculator from "./ROICalculator";
import BudgetCalculator from "./BudgetCalculator";
import CommissionCalculator from "./CommissionCalculator";
import RetirementCalculator from "./RetirementCalculator";
import BMRCalculator from "./BMRCalculator";
import CalorieCalculator from "./CalorieCalculator";
import IdealWeightCalculator from "./IdealWeightCalculator";
import GradeCalculator from "./GradeCalculator";
import PaceCalculator from "./PaceCalculator";


registerTool("word-counter", WordCounter);
registerTool("character-counter", CharacterCounter);
registerTool("text-case-converter", TextCaseConverter);
registerTool("text-reverser", TextReverser);
registerTool("json-formatter", JSONFormatter);
registerTool("base64-converter", Base64Converter);
registerTool("url-encoder", URLEncoder);
registerTool("url-slug-generator", URLSlugGenerator);
registerTool("morse-code-converter", MorseCodeConverter);
registerTool("csv-to-json", CSVToJSON);
registerTool("password-generator", PasswordGenerator);
registerTool("md5-hash", MD5Hash);
registerTool("sha256-hash", SHA256Hash);
registerTool("uuid-generator", UUIDGenerator);
registerTool("qr-code-generator", QRCodeGenerator);
registerTool("color-picker", ColorPicker);
registerTool("gradient-generator", GradientGenerator);
registerTool("bmi-calculator", BMICalculator);
registerTool("age-calculator", AgeCalculator);
registerTool("loan-calculator", LoanCalculator);
registerTool("emi-calculator", EMICalculator);
registerTool("percentage-calculator", PercentageCalculator);
registerTool("simple-interest", SimpleInterestCalculator);
registerTool("compound-interest", CompoundInterestCalculator);
registerTool("tip-calculator", TipCalculator);
registerTool("discount-calculator", DiscountCalculator);
registerTool("markup-calculator", MarkupCalculator);
registerTool("vat-calculator", VATCalculator);
registerTool("gpa-calculator", GPACalculator);
registerTool("factorial-calculator", FactorialCalculator);
registerTool("unit-converter", UnitConverter);
registerTool("temperature-converter", TemperatureConverter);
registerTool("weight-converter", WeightConverter);
registerTool("length-converter", LengthConverter);
registerTool("volume-converter", VolumeConverter);
registerTool("area-converter", AreaConverter);
registerTool("speed-converter", SpeedConverter);
registerTool("energy-converter", EnergyConverter);
registerTool("currency-converter", CurrencyConverter);
registerTool("stopwatch", Stopwatch);
registerTool("timer", Timer);
registerTool("time-calculator", TimeCalculator);
registerTool("uptime-calculator", UptimeCalculator);
registerTool("prime-checker", PrimeChecker);
registerTool("fibonacci-generator", FibonacciGenerator);
registerTool("roman-numeral", RomanNumeralConverter);
registerTool("hex-to-decimal", HexToDecimal);
registerTool("decimal-to-binary", DecimalToBinary);
registerTool("binary-to-decimal", BinaryToDecimal);
registerTool("hex-to-rgb", HexToRGB);
registerTool("rgb-to-hex", RGBToHex);
registerTool("distance-calculator", DistanceCalculator);
registerTool("text-to-speech", TextToSpeech);
registerTool("screen-resolution", ScreenResolution);
registerTool("qr-code-scanner", QRCodeScanner);
registerTool("regex-tester", RegexTester);
registerTool("jwt-decoder", JWTDecoder);
registerTool("unix-timestamp-converter", UnixTimestampConverter);
registerTool("html-entity-converter", HTMLEntityConverter);
registerTool("lorem-ipsum-generator", LoremIpsumGenerator);
registerTool("password-strength-checker", PasswordStrengthChecker);
registerTool("css-minifier", CSSMinifier);
registerTool("javascript-minifier", JavaScriptMinifier);
registerTool("meta-tag-generator", MetaTagGenerator);
registerTool("robots-txt-generator", RobotsTxtGenerator);
registerTool("xml-formatter", XMLFormatter);
registerTool("xml-to-json", XMLToJSON);
registerTool("json-to-xml", JSONToXML);
registerTool("html-formatter", HTMLFormatter);
registerTool("sql-formatter", SQLFormatter);
registerTool("url-parser", URLParser);
registerTool("cron-expression-generator", CronExpressionGenerator);
registerTool("hmac-generator", HMACGenerator);
registerTool("text-diff-checker", TextDiffChecker);
registerTool("color-contrast-checker", ColorContrastChecker);
registerTool("mortgage-calculator", MortgageCalculator);
registerTool("roi-calculator", ROICalculator);
registerTool("budget-calculator", BudgetCalculator);
registerTool("commission-calculator", CommissionCalculator);
registerTool("retirement-calculator", RetirementCalculator);
registerTool("bmr-calculator", BMRCalculator);
registerTool("calorie-calculator", CalorieCalculator);
registerTool("ideal-weight-calculator", IdealWeightCalculator);
registerTool("grade-calculator", GradeCalculator);
registerTool("pace-calculator", PaceCalculator);
