import { lazy } from "react";
import { registerTool } from "../toolRegistry";

const lazyTool = (loader) => lazy(loader);
const aiWorkspace = lazyTool(() => import('./ai/AIWorkspace'));
registerTool("ai-text-summarizer", aiWorkspace);
registerTool("ai-writing-assistant", aiWorkspace);
registerTool("ai-grammar-rewrite", aiWorkspace);
registerTool("ai-email-generator", aiWorkspace);
registerTool("ai-prompt-generator", aiWorkspace);
registerTool("ai-paraphraser", aiWorkspace);
registerTool("ai-blog-outline-generator", aiWorkspace);
registerTool("ai-title-generator", aiWorkspace);
registerTool("ai-social-caption-generator", aiWorkspace);
registerTool("ai-product-description-generator", aiWorkspace);
registerTool("ai-resume-bullet-generator", aiWorkspace);
registerTool("ai-cover-letter-assistant", aiWorkspace);
registerTool("ai-study-notes-generator", aiWorkspace);
registerTool("ai-faq-generator", aiWorkspace);
registerTool("ai-code-explainer", aiWorkspace);

registerTool("pdf-merger", lazyTool(() => import('./batch/PdfTools').then(m => ({ default:m.PDFMerger }))));
registerTool("pdf-splitter", lazyTool(() => import('./batch/PdfTools').then(m => ({ default:m.PDFSplitter }))));
registerTool("pdf-page-extractor", lazyTool(() => import('./batch/PdfTools').then(m => ({ default:m.PDFPageExtractor }))));
registerTool("images-to-pdf", lazyTool(() => import('./batch/PdfTools').then(m => ({ default:m.ImagesToPDF }))));
registerTool("pdf-to-images", lazyTool(() => import('./batch/PdfTools').then(m => ({ default:m.PDFToImages }))));
registerTool("image-resizer", lazyTool(() => import('./batch/ImageTools').then(m => ({ default:m.ImageResizer }))));
registerTool("image-cropper", lazyTool(() => import('./batch/ImageTools').then(m => ({ default:m.ImageCropper }))));
registerTool("image-converter", lazyTool(() => import('./batch/ImageTools').then(m => ({ default:m.ImageConverter }))));
registerTool("image-metadata-viewer", lazyTool(() => import('./batch/ImageTools').then(m => ({ default:m.ImageMetadataViewer }))));
registerTool("image-rotate-flip", lazyTool(() => import('./batch/ImageTools').then(m => ({ default:m.ImageRotateFlip }))));
registerTool("json-to-csv", lazyTool(() => import('./batch/DeveloperTools').then(m => ({ default:m.JSONToCSV }))));
registerTool("html-minifier", lazyTool(() => import('./batch/DeveloperTools').then(m => ({ default:m.HTMLMinifier }))));
registerTool("css-formatter", lazyTool(() => import('./batch/DeveloperTools').then(m => ({ default:m.CSSFormatter }))));
registerTool("javascript-formatter", lazyTool(() => import('./batch/DeveloperTools').then(m => ({ default:m.JavaScriptFormatter }))));

registerTool("word-counter", lazyTool(() => import("./WordCounter")));
registerTool("character-counter", lazyTool(() => import("./CharacterCounter")));
registerTool("text-case-converter", lazyTool(() => import("./TextCaseConverter")));
registerTool("text-reverser", lazyTool(() => import("./TextReverser")));
registerTool("json-formatter", lazyTool(() => import("./JSONFormatter")));
registerTool("base64-converter", lazyTool(() => import("./Base64Converter")));
registerTool("url-encoder", lazyTool(() => import("./URLEncoder")));
registerTool("url-slug-generator", lazyTool(() => import("./URLSlugGenerator")));
registerTool("morse-code-converter", lazyTool(() => import("./MorseCodeConverter")));
registerTool("csv-to-json", lazyTool(() => import("./CSVToJSON")));
registerTool("password-generator", lazyTool(() => import("./PasswordGenerator")));
registerTool("md5-hash", lazyTool(() => import("./MD5Hash")));
registerTool("sha256-hash", lazyTool(() => import("./SHA256Hash")));
registerTool("uuid-generator", lazyTool(() => import("./UUIDGenerator")));
registerTool("qr-code-generator", lazyTool(() => import("./QRCodeGenerator")));
registerTool("color-picker", lazyTool(() => import("./ColorPicker")));
registerTool("gradient-generator", lazyTool(() => import("./GradientGenerator")));
registerTool("bmi-calculator", lazyTool(() => import("./BMICalculator")));
registerTool("age-calculator", lazyTool(() => import("./AgeCalculator")));
registerTool("loan-calculator", lazyTool(() => import("./LoanCalculator")));
registerTool("emi-calculator", lazyTool(() => import("./EMICalculator")));
registerTool("percentage-calculator", lazyTool(() => import("./PercentageCalculator")));
registerTool("simple-interest", lazyTool(() => import("./SimpleInterestCalculator")));
registerTool("compound-interest", lazyTool(() => import("./CompoundInterestCalculator")));
registerTool("tip-calculator", lazyTool(() => import("./TipCalculator")));
registerTool("discount-calculator", lazyTool(() => import("./DiscountCalculator")));
registerTool("markup-calculator", lazyTool(() => import("./MarkupCalculator")));
registerTool("vat-calculator", lazyTool(() => import("./VATCalculator")));
registerTool("gpa-calculator", lazyTool(() => import("./GPACalculator")));
registerTool("factorial-calculator", lazyTool(() => import("./FactorialCalculator")));
registerTool("unit-converter", lazyTool(() => import("./UnitConverter")));
registerTool("temperature-converter", lazyTool(() => import("./TemperatureConverter")));
registerTool("weight-converter", lazyTool(() => import("./WeightConverter")));
registerTool("length-converter", lazyTool(() => import("./LengthConverter")));
registerTool("volume-converter", lazyTool(() => import("./VolumeConverter")));
registerTool("area-converter", lazyTool(() => import("./AreaConverter")));
registerTool("speed-converter", lazyTool(() => import("./SpeedConverter")));
registerTool("energy-converter", lazyTool(() => import("./EnergyConverter")));
registerTool("currency-converter", lazyTool(() => import("./CurrencyConverter")));
registerTool("stopwatch", lazyTool(() => import("./Stopwatch")));
registerTool("timer", lazyTool(() => import("./Timer")));
registerTool("time-calculator", lazyTool(() => import("./TimeCalculator")));
registerTool("uptime-calculator", lazyTool(() => import("./UptimeCalculator")));
registerTool("prime-checker", lazyTool(() => import("./PrimeChecker")));
registerTool("fibonacci-generator", lazyTool(() => import("./FibonacciGenerator")));
registerTool("roman-numeral", lazyTool(() => import("./RomanNumeralConverter")));
registerTool("hex-to-decimal", lazyTool(() => import("./HexToDecimal")));
registerTool("decimal-to-binary", lazyTool(() => import("./DecimalToBinary")));
registerTool("binary-to-decimal", lazyTool(() => import("./BinaryToDecimal")));
registerTool("hex-to-rgb", lazyTool(() => import("./HexToRGB")));
registerTool("rgb-to-hex", lazyTool(() => import("./RGBToHex")));
registerTool("distance-calculator", lazyTool(() => import("./DistanceCalculator")));
registerTool("text-to-speech", lazyTool(() => import("./TextToSpeech")));
registerTool("screen-resolution", lazyTool(() => import("./ScreenResolution")));
registerTool("qr-code-scanner", lazyTool(() => import("./QRCodeScanner")));
registerTool("regex-tester", lazyTool(() => import("./RegexTester")));
registerTool("jwt-decoder", lazyTool(() => import("./JWTDecoder")));
registerTool("unix-timestamp-converter", lazyTool(() => import("./UnixTimestampConverter")));
registerTool("html-entity-converter", lazyTool(() => import("./HTMLEntityConverter")));
registerTool("lorem-ipsum-generator", lazyTool(() => import("./LoremIpsumGenerator")));
registerTool("password-strength-checker", lazyTool(() => import("./PasswordStrengthChecker")));
registerTool("css-minifier", lazyTool(() => import("./CSSMinifier")));
registerTool("javascript-minifier", lazyTool(() => import("./JavaScriptMinifier")));
registerTool("meta-tag-generator", lazyTool(() => import("./MetaTagGenerator")));
registerTool("robots-txt-generator", lazyTool(() => import("./RobotsTxtGenerator")));
registerTool("xml-formatter", lazyTool(() => import("./XMLFormatter")));
registerTool("xml-to-json", lazyTool(() => import("./XMLToJSON")));
registerTool("json-to-xml", lazyTool(() => import("./JSONToXML")));
registerTool("html-formatter", lazyTool(() => import("./HTMLFormatter")));
registerTool("sql-formatter", lazyTool(() => import("./SQLFormatter")));
registerTool("url-parser", lazyTool(() => import("./URLParser")));
registerTool("cron-expression-generator", lazyTool(() => import("./CronExpressionGenerator")));
registerTool("hmac-generator", lazyTool(() => import("./HMACGenerator")));
registerTool("text-diff-checker", lazyTool(() => import("./TextDiffChecker")));
registerTool("color-contrast-checker", lazyTool(() => import("./ColorContrastChecker")));
registerTool("mortgage-calculator", lazyTool(() => import("./MortgageCalculator")));
registerTool("roi-calculator", lazyTool(() => import("./ROICalculator")));
registerTool("budget-calculator", lazyTool(() => import("./BudgetCalculator")));
registerTool("commission-calculator", lazyTool(() => import("./CommissionCalculator")));
registerTool("retirement-calculator", lazyTool(() => import("./RetirementCalculator")));
registerTool("bmr-calculator", lazyTool(() => import("./BMRCalculator")));
registerTool("calorie-calculator", lazyTool(() => import("./CalorieCalculator")));
registerTool("ideal-weight-calculator", lazyTool(() => import("./IdealWeightCalculator")));
registerTool("grade-calculator", lazyTool(() => import("./GradeCalculator")));
registerTool("pace-calculator", lazyTool(() => import("./PaceCalculator")));

registerTool("image-compressor", lazyTool(() => import("./ImageCompressor")));
